### ISSUE TITLE
Backend Error when creating subnet

### ISSUE THREAD

**Issue by r0fls** [kelseyhightower/kubernetes-the-hard-way#195]
After following the steps up to the creation of the subnet, I get the below result:

```
 $ gcloud compute networks subnets create kubernetes   --network kubernetes-the-hard-way   --range 10.240.0.0/24   --region us-west2
ERROR: (gcloud.compute.networks.subnets.create) Could not fetch resource:
 - Backend Error
```

I can see the kubernetes-the-hard-way network exists:

```
 $ gcloud compute networks list
NAME                     MODE    IPV4_RANGE  GATEWAY_IPV4
default                  auto
kubernetes-the-hard-way  custom
```

Are there any recommendations for troubleshooting?

**Comment by r0fls** [comment]
Enabling debug verbosity level I get slightly more info:

```
$ gcloud compute networks subnets create kubernetes --network kubernetes-the-hard-way   --range 10.240.0.0/24   --region us-west2 --verbosity
 debug
DEBUG: Running [gcloud.compute.networks.subnets.create] with arguments: [--network: "kubernetes-the-hard-way", --range: "10.240.0.0/24", --region: "us-west2", --ver
 --verbosity: "debug", NAME: "kubernetes"]
DEBUG: (gcloud.compute.networks.subnets.create) Could not fetch resource:
 - Backend Error
Traceback (most recent call last):
  File "/Users/raphael.deem/Documents/code/go/src/git.tmaws.io/core-platform/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 811, in Execute
    resources = args.calliope_command.Run(cli=self, args=args)
  File "/Users/raphael.deem/Documents/code/go/src/git.tmaws.io/core-platform/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 784, in Run
    resources = command_instance.Run(args)
  File "/Users/raphael.deem/Documents/code/go/src/git.tmaws.io/core-platform/google-cloud-sdk/lib/surface/compute/networks/subnets/create.py", line 85, in Run
    'Insert', request)])
  File "/Users/raphael.deem/Documents/code/go/src/git.tmaws.io/core-platform/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/client_adapter.py", line 89, in Mak
in MakeRequests
    errors, error_message='Could not fetch resource:')
  File "/Users/raphael.deem/Documents/code/go/src/git.tmaws.io/core-platform/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 106, in RaiseToolEx
ToolException
    RaiseException(problems, calliope_exceptions.ToolException, error_message)
  File "/Users/raphael.deem/Documents/code/go/src/git.tmaws.io/core-platform/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 118, in RaiseExcept
Exception
    errors))
ToolException: Could not fetch resource:
 - Backend Error

ERROR: (gcloud.compute.networks.subnets.create) Could not fetch resource:
 - Backend Error```

**Comment by r0fls** [comment]
bleh, i should have just used the default region.
